site_name: beambusters
repo_url: https://github.com/anananacr/beambusters.git
repo_name: beambusters

theme:
  name: material
  favicon: assets/icon.png
  logo: assets/icon.png
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    primary: cyan
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/typewriter.css
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            extra:
              show_submodule: true
              show_root_heading: true
              show_root_full_path: false
              show_root_toc_entry: false
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - About beambusters: reference/index.md
  - Installation: reference/install.md
  - Usage: reference/usage.md
  - Examples:
      - Configuration: example/config.md
  - Contact: reference/contact.md
  - API Reference:
      - main CLI: reference/main.md
      - algorithms: reference/algorithms.md
      - settings: reference/settings.md
      - utils: reference/utils.md
