geometry_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/geoms/jungfrau-1m-vertical-v1-100mm.geom
output_path: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria

calibration: 
  skip: true
  calibration_files_directory: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria/darks

plots:
  flag: false
  file_name: lyso
  folder_name: lyso_sweep
  root_path: /home/rodria/bb

force_center:
  mode: false
  x: 572
  y: 465

search_radius: 4

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 4
  min_pixel_count: 3
  max_pixel_count: 1000
  local_bg_radius: 5
  min_res: 0
  max_res: 600

starting_frame: 500

offset:
  x: 0
  y: 0

peak_region:
  min: 40
  max: 60

outlier_distance: 35

canny:
  sigma: 3
  low_threshold: 0.95
  high_threshold: 0.99

method: circle_detection

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 5

skip_methods:
  - minimize_peak_fwhm

polarization:
  skip: false
  axis: x
  value: 0.99