raw_data_list_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/lists/split_lyso_02_events.lst05
geometry_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/geoms/jungfrau-1m-vertical-v0-70mm.geom
output_path: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria

calibration: 
  skip: true
  calibration_files_directory: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria/darks

plots:
  flag: true
  file_name: beam_sweeping_test_lyso_02
  folder_name: beam_sweeping_test_lyso_02
  root_path: /home/rodria/bb

force_center:
  mode: true
  x: 556
  y: 522

search_radius: 7

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 4
  min_pixel_count: 2
  max_pixel_count: 100000
  local_bg_radius: 3
  min_res: 0
  max_res: 1200

starting_frame: 400

offset:
  x: 0
  y: 0

peak_region:
  min: 80
  max: 100

outlier_distance: 20

canny:
  sigma: 3
  low_threshold: 0.98
  high_threshold: 0.99

method: circle_detection

bragg_peaks_positions_for_center_of_mass_calculation: 0

pixels_for_mask_of_bragg_peaks: 4

skip_methods:
  - minimize_peak_fwhm
  

polarization:
  skip: false
  axis: x
  value: 0.99