geometry_file: /asap3/fs-bmx/gpfs/regae/2023/data/11018148/processed/rodria/geoms/JF_regae_v0.geom
output_path: /asap3/fs-bmx/gpfs/regae/2023/data/11018148/processed/rodria/

calibration: 
  skip: true
  calibration_files_directory: /folder/to/darks

plots:
  flag: false
  file_name: mica_dez
  folder_name: mica_dez
  root_path: /home/rodria/bb

force_center:
  mode: true
  x: 481
  y: 544

search_radius: 12

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 2
  max_pixel_count: 100000
  local_bg_radius: 5
  min_res: 0
  max_res: 250

starting_frame: 0

offset:
  x: 0
  y: 0

peak_region:
  min: 0
  max: 0

outlier_distance: 20

canny:
  sigma: 0
  low_threshold: 0.0
  high_threshold: 0.0

method: center_of_massŝ

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 8

skip_methods:
  - minimize_peak_fwhm
  
polarization:
  skip: true
  axis: x
  value: 0.99