raw_data_list_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria/lists/fakp_a06_01_test.lst
geometry_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria/geoms/jungfrau-1m.geom
output_path: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria

calibration: 
  skip: false
  calibration_files_directory: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/scratch_cc/rodria/darks

plots:
  flag: false
  file_name: beam_sweeping_test
  folder_name: beam_sweeping_test
  root_path: /home/rodria/beam_sweeping_test

force_center:
  mode: false
  x: 560
  y: 532

search_radius: 18

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 5
  max_pixel_count: 100000
  local_bg_radius: 10
  min_res: 20
  max_res: 150

starting_frame: 0

offset:
  x: 0
  y: 0

peak_region:
  min: 0
  max: 0

outlier_distance: 20

canny:
  sigma: 0
  low_threshold: 0
  high_threshold: 0

method: center_of_mass

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 8

skip_methods:
  - minimize_peak_fwhm
  - circle_detection
  - friedel_pairs
  - center_of_mass

polarization:
  skip: true
  axis: x
  value: 0.99