geometry_file: /path/to/geom/detector.geom

chunks: 100
number_of_processors: 4

burst_mode:
  state: false
  storage_cell_hdf5_path: /entry/data/storage_cell_number

vds_format: false

plots:
  flag: false
  maximum_number_of_frames: 50
  file_name: my_sample_label
  folder_name: run_label
  root_path: /path/to/plots
  value_auto: true
  value_min: 0
  value_max: 0
  axis_lim_auto: true
  xlim_min: 0
  xlim_max: 0
  ylim_min: 0
  ylim_max: 0
  color_map: viridis
  marker_size: 200

force_center:
  state: true
  anchor_x: true
  anchor_y: true
  x: 454
  y: 538

search_radius: 8

pf8:
  min_num_peaks: 1
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 4
  max_pixel_count: 100000
  local_bg_radius: 9
  min_res: 0
  max_res: 250

starting_frame: 600

peak_region:
  min: 0
  max: 0

canny:
  sigma: 3
  low_threshold: 0.9
  high_threshold: 0.99

hough:
  maximum_rank:
  outlier_distance:
    x: 0
    y: 0

offset:
  x: 0.5
  y: 0.5

outlier_distance:
  x: 20
  y: 20

reference_center:
  x: 454
  y: 538

centering_method_for_initial_guess: center_of_mass

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 8

skip_centering_methods:
  - minimize_peak_fwhm
  - circle_detection

polarization:
  apply_polarization_correction: false
  axis: x
  value: 0.99
