geometry_file: /Users/minoru/Documents/ana/scripts/beambusters/docs/example/simple.geom
output_hdf5_root_path: /data/data

burst_mode:
  is_active: false
  storage_cell_hdf5_path: /data/data/storage_cell_number

chunks: 500
number_of_processors: 16

vds_format: false
vds_id: generic

plots:
  flag: false

force_center:
  state: false
  anchor_x: false
  anchor_y: false
  x: 554
  y: 522

search_radius: 10

pf8:
  min_num_peaks: 0
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 2
  max_pixel_count: 20
  local_bg_radius: 5
  min_res: 0
  max_res: 4000

starting_frame: 0

offset:
  x: 0.5
  y: 0.5

peak_region:
  min: 50
  max: 70

outlier_distance:
  x: 10
  y: 100

reference_center:
  x: 554
  y: 522

canny:
  sigma: 3
  low_threshold: 0.9
  high_threshold: 0.99

hough:
  maximum_rank: 10
  outlier_distance:
    x: 10
    y: 100

centering_method_for_initial_guess: circle_detection

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 4

skip_centering_methods:
  - minimize_peak_fwhm

polarization:
  apply_polarization_correction: true
  axis: x
  value: 0.99
