geometry_file: # Absolute path to the geometry file. Type: str
input_path:  # Absolute path to the input path. Type: str
output_path:  # Absolute path to the output path. Type: str

burst_mode: # Indicate if the detector is on burst mode. 
  state: # Burst/storage cell mode (true) or single cell mode (false). Type: bool.
  storage_cell_hdf5_path: # Absolute HDF5 path to the storage cell id per frame. Type: str
  debug_hdf5_path: # Absolute HDF5 path to the debug value per frames. Type: str

compression:
  compress_data: # Indicate if the output data should be compressed (true) or not (false). Type: bool.
  filter: # Label of the compression filter to be used, for example: gzip. Type: str.
  opts: # Options of the compression filter. Type: int.

plots:
  flag:  # Indicate if plots should be saved in intermediate steps (true) or not (false). Type: bool.
  maximum_number_of_frames: # Number of frames to save plots. Type: int
  file_name: # The plots file name for saving. Type: str.
  folder_name: # The plots folder name for saving. Type: str.
  root_path: # Absolute path for the root directory for saving. Plots final state is /root_path/folder_name/*/file_name_*.png. Type: str.
  value_auto: # Control the automatic intensity adjustment of plots level (true). The normalization used is in logarithmic scale. Type: bool.
  value_min: # If value_auto is false, minimum value of the intensity level should be passed. The normalization used is in logarithmic scale. Type: int.
  value_max: # If value_auto is false, maximum value of the intensity level should be passed. The normalization used is in logarithmic scale. Type: int.
  axis_lim_auto: # Control the automatic axis limits of the plots (true). Type: bool.
  xlim_min: # If axis_lim_auto is false, minimum coordinate of the x axis should be passed. Type: int.
  xlim_max: # If axis_lim_auto is false, maximum coordinate of the x axis should be passed. Type: int.
  ylim_min: # If axis_lim_auto is false, minimum coordinate of the y axis should be passed. Type: int.
  ylim_max: # If axis_lim_auto is false, maximum coordinate of the y axis should be passed. Type: int.
  color_map: # Colormap preference for the plots, for example: viridis. Type: str.

starting_frame: # Change the index of the starting frame, it will jump the first n images of the container file. Type: int.

force_center: # Anchor the initial guess to a fixed point, if enabled this option will override other bblib pre-centering methods.
  state: # Turn force mode on (true) or off (false). Type: bool.
  anchor_x: # Turn force mode on (true) or off (false) for the x-axis. Type: bool.
  anchor_y: # Turn force mode on (true) or off (false) for the y-axis . Type: bool.
  x: # Initial guess pixel coordinates in x of the assembled data, i.e. image stored in a single array with the detector panels' geometric transformations applied, according to CrystFEL referential convention. Type: int.
  y: # Initial guess pixel coordinates in y of the assembled data, i.e. image stored in a single array with the detector panels' geometric transformations applied, according to CrystFEL referential convention. Type: int.

search_radius: # Search radius used in the FriedelPairs bblib method. Type: float

pf8: # peakfinder8 paratemers for Bragg peaks search. For more information, see: https://www.desy.de/~barty/cheetah/Cheetah/SFX_hitfinding.html
  max_num_peaks: #  Maximum number of peaks. Type: int
  adc_threshold: # Arbitrary detector counts (ADC) threshold. Type: int
  minimum_snr: # Minimum signal-to-noise ratio (SNR). Type: float
  min_pixel_count: # Minimum number of pixels to consider a peak. Type: int
  max_pixel_count: # Maximum number of pixels to consider a peak. Type: int
  local_bg_radius: # Radius of the peaks local background, in pixels. Type: int
  min_res: # Minimum resolution region, in pixels. Type: int
  max_res: # Maximum resolution region, in pixels. Type: int

offset: # Add an offset to the calculated center. The offset will be applied in the end of every bblib centering method. Set offsets to +0.5 in x and y to shift the detector center coordinates from pixel indices to the pixel center, as expected for CrystFEL.
  x: # Offset in x direction, in pixels. Type: int
  y: # Offset in y direction, in pixels. Type: int

peak_region: # Defines the approximate background peak distance from the center of the diffraction pattern, in pixels. This option is used in CircleDetection bblib pre-centering methods.
  min: # Minimum distance, in pixels, of the background peak to the center of the diffraction pattern. Type: int
  max: # Maximum distance, in pixels, of the background peak to the center of the diffraction pattern. Type: int

outlier_distance: # Don't refine the detector center with FriedelPairs method if the initial_guess distance to the reference_center coordinates is bigger than the outlier_distance.

reference_center: # Reference center of the diffraction pattern to filter outliers in the initial_guess calculation
  x: # Reference center pixel coordinates in x of the assembled data, i.e. image stored in a single array with the detector panels' geometric transformations applied, according to CrystFEL referential convention. Type: int
  y: # Reference center pixel coordinates in y of the assembled data, i.e. image stored in a single array with the detector panels' geometric transformations applied, according to CrystFEL referential convention. Type: int

canny: # Controls skimage.feature.canny function, used in the CircleDetection bblib method. For more information, see: https://scikit-image.org/docs/stable/auto_examples/edges/plot_circular_elliptical_hough_transform.html
  sigma: # Standard deviation of the Gaussian filter, used in the Canny function. Usually, 3 is good. Type: float
  low_threshold: # Lower bound for hysteresis thresholding (linking edges), as quantiles of the edge magnitude image. Threshold must be in the range [0, 1). Usually, 0.9 is good. Type: float
  high_threshold: # Upper bound for hysteresis thresholding (linking edges), as quantiles of the edge magnitude images. Threshold must be in the range [0, 1). Usually, 0.99 is good. Type: float

centering_method_for_initial_guess: # Choose the bblib pre-centering method for the initial_guess assignment. Options: 'center_of_mass' or 'circle_detection'. Type: str

bragg_peaks_positions_for_center_of_mass_calculation: # Choose if Bragg peaks should be masked out (0) from the image in the CenterOfMass bblib method, or use only the Bragg peaks (1), or use the image as it is (-1). Type: int

pixels_for_mask_of_bragg_peaks: # Radius of Bragg peaks, in pixels. Used in the bblib pre-centering methods. Type: int

skip_centering_methods: # List of bblib pre-centering methods you don't want to be executed. Options: 'center_of_mass', 'circle_detection' or 'friedel_pairs'. Type: List[str]
  - # Method label you want to skip. Type: str

polarization: # Configure the polarization correction before refining the center in the FridelPairs bblib method. 
  apply_polarization_correction: # Aoply polarization correction (true) or not (false). Type: bool
  axis: # Polarization axis direction. Options: 'x' and 'y', as defined by the CrystFEL referential convention. Type: str
  value: # Polarization fraction in the axis direction. Type: float