geometry_file: /asap3/fs-bmx/gpfs/regae/2023/data/11018148/processed/rodria/geoms/JF_regae_v2.geom
input_path: /asap3/fs-bmx/gpfs/regae/2023/data/11018148/processed/converted
output_path: /asap3/fs-bmx/gpfs/regae/2023/data/11018148/processed/rodria/test

burst_mode: 
  state: false
  storage_cell_hdf5_path: /entry/data/storage_cell_number
  debug_hdf5_path: /entry/data/debug

compression:
  compress_data: false
  filter: gzip
  opts: 6

plots:
  flag: false
  maximum_number_of_frames: 50
  file_name: mica_dez
  folder_name: mica_dez_flip
  root_path: /home/rodria/bb
  value_auto: true
  value_min: 0
  value_max: 0
  axis_lim_auto: true
  xlim_min: 0
  xlim_max: 0
  ylim_min: 0 
  ylim_max: 0
  color_map: viridis
  
  
force_center:
  state: true
  x: 454
  y: 538

search_radius: 8

pf8:
  max_num_peaks: 10000
  adc_threshold: 0
  minimum_snr: 5
  min_pixel_count: 4
  max_pixel_count: 100000
  local_bg_radius: 9
  min_res: 0
  max_res: 250

starting_frame: 600


offset:
  x: 0
  y: 0

peak_region:
  min: 0
  max: 0

outlier_distance: 20

reference_center:
  x: 454
  y: 538

canny:
  sigma: 0
  low_threshold: 0.0
  high_threshold: 0.0

centering_method_for_initial_guess: center_of_mass

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 8

skip_centering_methods:
  - minimize_peak_fwhm
  
polarization:
  skip: true
  axis: x
  value: 0.99