geometry_file: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/geoms/jungfrau-1m-vertical-v1-100mm-shift.geom
input_path: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/converted
output_path: /gpfs/cfel/group/cxi/scratch/2021/ESRF-2024-Meents-Mar-ID09/processed/rodria/centered

burst_mode: 
  is_active: false
  storage_cell_hdf5_path: /entry/data/storage_cell_number
  debug_hdf5_path: /entry/data/debug

compression:
  compress_output_data: false
  filter: gzip
  opts: 6

plots:
  flag: true
  maximum_number_of_frames: 50
  file_name: fakp
  folder_name: fakp_apo
  root_path: /home/rodria/bb
  value_auto: false
  value_min: 1e0
  value_max: 5e2
  axis_lim_auto: false
  xlim_min: 200
  xlim_max: 900
  ylim_min: 200
  ylim_max: 900
  color_map: viridis

force_center:
  state: false
  x: 554
  y: 522

search_radius: 4.5

pf8:
  max_num_peaks: 10000
  adc_threshold: 100
  minimum_snr: 5
  min_pixel_count: 2
  max_pixel_count: 10000
  local_bg_radius: 5
  min_res: 0
  max_res: 600

starting_frame: 500

offset:
  x: 0
  y: 0

peak_region:
  min: 50
  max: 70

outlier_distance: 10

reference_center:
  x: 554
  y: 522

canny:
  sigma: 3
  low_threshold: 0.9
  high_threshold: 0.99

centering_method_for_initial_guess: circle_detection

bragg_peaks_positions_for_center_of_mass_calculation: -1

pixels_for_mask_of_bragg_peaks: 4

skip_centering_methods:
  - minimize_peak_fwhm

polarization:
  apply_polarization_correction: true
  axis: x
  value: 0.99